import { Assessment, User } from '../types';

export const INITIAL_USERS: User[] = [
  { id: 'dev1', email: 'dev@pagalungan.gov.ph', name: 'System Developer', role: 'DEVELOPER' },
  { id: 'mod1', email: 'mod@pagalungan.gov.ph', name: 'Chief Moderator', role: 'MODERATOR' },
  { id: 'op1', email: 'op@pagalungan.gov.ph', name: 'Data Operator', role: 'OPERATOR' },
  { id: 'guest1', email: 'guest@public.com', name: 'Juan Dela Cruz', role: 'GUEST' },
];

export const INITIAL_ASSESSMENTS: Assessment[] = [
  {
    id: '1',
    td_Number: 'TD-2024-001',
    owner_name: 'Santiago, Maria L.',
    td_barangay: 'Poblacion',
    lot_No: 'Lot-123-A',
    title_No: 'T-45321',
    td_Kind: 'Land',
    td_Class: 'Commercial',
    land_Area: 0.05,
    market_Value: 1500000,
    assessed_Value: 600000,
    tax_Due: 12000,
    td_Effectivity: 2024,
    td_Previous: 'TD-2020-998',
    td_Cancelled: '',
    td_Status: 'Taxable',
    createdBy: { userId: 'op1', name: 'Data Operator' },
    comments: []
  },
  {
    id: '2',
    td_Number: 'TD-2024-002',
    owner_name: 'Pagalungan Central School',
    td_barangay: 'Poblacion',
    lot_No: 'Lot-Gov-1',
    title_No: 'Special Patent',
    td_Kind: 'Building',
    td_Class: 'Educational',
    land_Area: 2.5,
    market_Value: 5000000,
    assessed_Value: 0,
    tax_Due: 0,
    td_Effectivity: 2023,
    td_Previous: '',
    td_Cancelled: '',
    td_Status: 'Exempt',
    createdBy: { userId: 'dev1', name: 'System Developer' },
    comments: [
      { id: 'c1', authorName: 'Concerned Citizen', text: 'Does this include the new gym?', timestamp: Date.now() - 100000, isDeveloperReply: false }
    ]
  },
  {
    id: '3',
    td_Number: 'TD-2024-003',
    owner_name: 'Pendatun, Abdul K.',
    td_barangay: 'Galakit',
    lot_No: 'Lot-888',
    title_No: 'OCT-12',
    td_Kind: 'Land',
    td_Class: 'Agricultural',
    land_Area: 5.0,
    market_Value: 250000,
    assessed_Value: 100000,
    tax_Due: 1000,
    td_Effectivity: 2022,
    td_Previous: '',
    td_Cancelled: '',
    td_Status: 'Taxable',
    createdBy: { userId: 'op1', name: 'Data Operator' },
    comments: []
  },
  {
    id: '4',
    td_Number: 'TD-2023-Old',
    owner_name: 'Unknown Owner',
    td_barangay: 'Layog',
    lot_No: 'Unknown',
    title_No: '',
    td_Kind: 'Land',
    td_Class: 'Others',
    land_Area: 1.0,
    market_Value: 50000,
    assessed_Value: 20000,
    tax_Due: 0,
    td_Effectivity: 2020,
    td_Previous: '',
    td_Cancelled: '',
    td_Status: 'No Data',
    createdBy: { userId: 'dev1', name: 'System Developer' },
    comments: []
  },
  {
    id: '5',
    td_Number: 'TD-2024-005',
    owner_name: 'Santos, Jose',
    td_barangay: 'Buliok',
    lot_No: 'Lot-55',
    title_No: 'T-1122',
    td_Kind: 'Machinery',
    td_Class: 'Industrial',
    land_Area: 0,
    market_Value: 800000,
    assessed_Value: 400000,
    tax_Due: 8000,
    td_Effectivity: 2024,
    td_Previous: '',
    td_Cancelled: '',
    td_Status: 'Taxable',
    createdBy: { userId: 'mod1', name: 'Chief Moderator' },
    comments: []
  },
  {
    id: '6',
    td_Number: 'TD-CANCELLED',
    owner_name: 'Dela Cruz, Juan',
    td_barangay: 'Kudal',
    lot_No: 'Lot-X',
    title_No: '',
    td_Kind: 'Building',
    td_Class: 'Residential',
    land_Area: 0.02,
    market_Value: 200000,
    assessed_Value: 0,
    tax_Due: 0,
    td_Effectivity: 2021,
    td_Previous: '',
    td_Cancelled: 'Assessor Office',
    td_Status: 'Cancelled',
    createdBy: { userId: 'op1', name: 'Data Operator' },
    comments: []
  }
];